### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Atzerkins** [lorsabyan/imusic.am-downloader#1]
Hi, I tried using your extension but unfortunately I don't seem to be able to make it work.

I checked the console for the background page too, there isn't anything either. I can get errors if I click the extension's button on a newtab for example but when it's on imusic, nothing seems to happen at all and I can't figure out what's wrong.

**Comment by lorsabyan** [comment]
Hi @Atzerkins,

The extension downloads the current playing music from the https://imusic.am.

I just checked the functionality and it's working. The only case could be the slow internet connection. The script downloads from the current stream then tries to save. This action lasts couple of seconds on good internet connection.

**Comment by lorsabyan** [comment]
Closing this issue.
